services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    container_name: geek-cloudflare-ddns
    restart: unless-stopped
    read_only: true
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    env_file:
      - /etc/homelab/secrets/cloudflare-ddns.env
    environment:
      - PROXIED=false
      - UPDATE_CRON=@every 5m
      - IP_NETWORKS=all
